"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { FileText, Download, Loader2, Share2 } from "lucide-react"
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { toast } from "sonner"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

interface ReportGeneratorProps {
    data: any
    aiInsights?: any
    datasetName: string
}

export function ReportGenerator({ data, aiInsights, datasetName }: ReportGeneratorProps) {
    const [isGenerating, setIsGenerating] = useState(false)

    const generatePDF = async () => {
        setIsGenerating(true)
        try {
            const doc = new jsPDF()
            const pageWidth = doc.internal.pageSize.getWidth()

            // Header
            doc.setFillColor(20, 20, 20)
            doc.rect(0, 0, pageWidth, 40, 'F')

            doc.setTextColor(255, 255, 255)
            doc.setFontSize(24)
            doc.text("InsightHub Analytics Report", 20, 20)

            doc.setFontSize(12)
            doc.setTextColor(200, 200, 200)
            doc.text(`Dataset: ${datasetName}`, 20, 32)
            doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 60, 32)

            let yPos = 50

            // Executive Summary (AI Insights)
            if (aiInsights && aiInsights.insights?.length > 0) {
                doc.setTextColor(0, 0, 0)
                doc.setFontSize(16)
                doc.text("Executive Summary", 20, yPos)
                yPos += 10

                doc.setFontSize(11)
                aiInsights.insights.forEach((insight: string) => {
                    const splitText = doc.splitTextToSize(`• ${insight}`, pageWidth - 40)
                    doc.text(splitText, 25, yPos)
                    yPos += (splitText.length * 7)
                })
                yPos += 10
            }

            // Data Quality Score
            doc.setFillColor(245, 245, 245)
            doc.roundedRect(20, yPos, pageWidth - 40, 30, 3, 3, 'F')

            doc.setFontSize(14)
            doc.text("Data Quality Score", 30, yPos + 12)

            doc.setFontSize(20)
            const score = data.data_quality_score?.overall_score || 0
            if (score > 80) doc.setTextColor(22, 163, 74) // Green
            else if (score > 60) doc.setTextColor(202, 138, 4) // Yellow
            else doc.setTextColor(220, 38, 38) // Red

            doc.text(`${score.toFixed(1)}%`, pageWidth - 50, yPos + 12)

            doc.setFontSize(10)
            doc.setTextColor(100, 100, 100)
            doc.text(`Rating: ${data.data_quality_score?.rating || 'N/A'}`, pageWidth - 50, yPos + 22)

            yPos += 40

            // Column Statistics Table
            doc.setTextColor(0, 0, 0)
            doc.setFontSize(16)
            doc.text("Column Statistics", 20, yPos)
            yPos += 5

            const tableData = data.columns.map((col: any) => [
                col.name,
                col.dtype,
                col.missing_percentage.toFixed(1) + '%',
                col.unique_count,
                col.mean ? col.mean.toFixed(2) : '-'
            ])

            autoTable(doc, {
                startY: yPos,
                head: [['Column', 'Type', 'Missing', 'Unique', 'Mean']],
                body: tableData,
                theme: 'grid',
                headStyles: { fillColor: [40, 40, 40] },
                margin: { top: 20 },
            })

            // @ts-ignore
            yPos = doc.lastAutoTable.finalY + 20

            // Recommendations
            if (aiInsights && aiInsights.recommendations?.length > 0) {
                if (yPos > doc.internal.pageSize.getHeight() - 60) {
                    doc.addPage()
                    yPos = 30
                }

                doc.setFontSize(16)
                doc.text("Optimization Recommendations", 20, yPos)
                yPos += 10

                doc.setFontSize(11)
                aiInsights.recommendations.forEach((rec: string) => {
                    const splitText = doc.splitTextToSize(`→ ${rec}`, pageWidth - 40)
                    doc.text(splitText, 25, yPos)
                    yPos += (splitText.length * 7)
                })
            }

            // Footer
            const pageCount = doc.internal.getNumberOfPages()
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i)
                doc.setFontSize(10)
                doc.setTextColor(150, 150, 150)
                doc.text(`Generated by InsightHub - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })
            }

            doc.save(`InsightHub_Report_${datasetName.replace(/\s+/g, '_')}.pdf`)
            toast.success("Report generated successfully")
        } catch (error) {
            console.error("PDF Generation Error:", error)
            toast.error("Failed to generate report")
        } finally {
            setIsGenerating(false)
        }
    }

    return (
        <DropdownMenu>
            <DropdownMenuTrigger asChild>
                <Button variant="outline" className="gap-2 border-blue-500/20 hover:bg-blue-500/10 hover:text-blue-400">
                    {isGenerating ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                        <FileText className="h-4 w-4" />
                    )}
                    Generate Report
                </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-48 bg-zinc-950 border-white/10">
                <DropdownMenuItem onClick={generatePDF} className="cursor-pointer gap-2 text-zinc-300 focus:bg-white/5 focus:text-white">
                    <Download className="h-4 w-4" />
                    Download PDF
                </DropdownMenuItem>
                <DropdownMenuItem disabled className="gap-2 text-zinc-500 cursor-not-allowed">
                    <Share2 className="h-4 w-4" />
                    Share (Coming Soon)
                </DropdownMenuItem>
            </DropdownMenuContent>
        </DropdownMenu>
    )
}
